version: "4"

services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 8080:80
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      - NODE_ENV=production
      - PORT=5000
      - JWT_SECRET
      - MONGO_URI
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend/web
    volumes:
      - /app/node_modules
      - /app/src/styles
      - ./frontend/web:/app
    environment:
      - NODE_ENV=production
      - REACT_APP_PRODUCTION_API_ENDPOINT