version: "3"

volumes:
  uploads: {}

services:
  mongo:
    image: mongo:6.0.1
    restart: on-failure
    env_file:
      - ./mongo/.env
    volumes:
      - ./mongo/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017
  api:
    depends_on:
      - mongo
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    command: sh -c "yarn && yarn dev"
    volumes:
       - ./api:/app
    # depends_on:
    #   - mongo
    # build:
    #   context: ./api
    #   dockerfile: Dockerfile
    # volumes:
    #   - uploads:/uploads
    # env_file:
    #   - ./api/.env
  frontend:
    depends_on:
      - api
    build:
      context: ./web
      dockerfile: Dockerfile
    env_file:
      - ./web/.env.local
  nginx:
    depends_on:
      - api
      - frontend
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80