version: "3"

volumes:
  uploads: {}

services:
  mongo:
    image: mongo:6.0.1
    restart: always
    env_file:
      - ./mongo/.env
    volumes:
      - ./mongo/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017
  api:
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile.dev
    volumes:
      - .:/app
      - uploads:/uploads
    env_file:
      - ./apps/api/.env
    command: turbo run dev --scope="api"
  frontend:
    depends_on:
      - api
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile.dev
    volumes:
      - .:/app
    env_file:
      - ./apps/web/.env.local
    command: turbo run dev --scope="web"
  nginx:
    depends_on:
      - api
      - frontend
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80