version: "3"

volumes:
 database-data:
 minio-storage:

services:
  traefik:
    image: traefik
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.minioentry.address=:9001
    ports:
      - 80:80
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  minio:
    image: minio/minio:latest
    restart: always
    command: server --console-address ":9001" /data/
    environment:
      MINIO_ROOT_USER: vai
      MINIO_ROOT_PASSWORD: vaiminiopass
    volumes:
      - minio-storage:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.minio.rule=Host(`127.0.0.1`)
      - traefik.http.routers.minio.entrypoints=minioentry
      - traefik.http.services.minio.loadbalancer.server.port=9001

  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - database-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_SERVER=db
    depends_on:
      - db
      - minio
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.rule=Host(`localhost`)
      - traefik.http.routers.backend.entrypoints=web
      - traefik.http.services.backend.loadbalancer.server.port=3000
