version: "3"

services:
  mongo:
    image: mongo:6.0.1
    restart: on-failure
    env_file:
      - ./mongo/.env
    volumes:
      - ./mongo/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017
  api:
    depends_on:
      - mongo
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    command: sh -c "yarn && yarn dev"
    volumes:
       - ./api:/app
  frontend:
    depends_on:
      - api
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    command: sh -c "yarn && yarn dev"
    volumes:
       - ./web:/app
  nginx:
    depends_on:
      - api
      - frontend
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80