version: "3"

services:
  mongo:
    image: mongo:6.0.1
    restart: always
    env_file:
      - ./mongo/.env
    volumes:
      - ./mongo/.initdb.js:/docker-entrypoint-initdb.d/initdb.js
  mongo-express:
    depends_on:
      - mongo
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - ./mongo-express/.env
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
  api:
    depends_on:
      - mongo
      - nginx
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - .:/app
    env_file:
      - ./apps/api/.env
    command: turbo run dev --scope="api"
  frontend:
    depends_on:
      - api
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - .:/app
    env_file:
      - ./apps/web/.env.local
    command: turbo run dev --scope="web"
